twitter-bot:
  build: ./twitter-bot
  volumes:
   - /var/somewhere2
   - ./twitter-bot:/twitter-bot
  env_file: ./twitter-bot/keys.env
  links:
    - imagenet-proxy:imagenet
imagenet-proxy:
  image: tutum/haproxy
  links:
    - imagenet
imagenet:
  build: ./imagenet-service
  volumes:
   - ./imagenet-service:/imagenet
checklist:
  build: ./checklist
  command: "gulp"
  ports:
   - 3000:3000
  volumes_from:
   - twitter-bot
  volumes:
   - ./checklist:/checklist
