imagenet:
  build: ./imagenet-service
  ports:
   - "5000:80"
  volumes:
   - ./imagenet-service:/imagenet
twitter-bot:
  build: ./twitter-bot
  volumes:
   - ./twitter-bot:/twitter-bot
  env_file: ./twitter-bot/keys.env
  links:
    - imagenet-proxy:imagenet
imagenet-proxy:
  image: tutum/haproxy
  links:
    - imagenet
     
